@echo off
echo Starting Viswam Report Card App...

echo Starting Backend (Port 5000)...
start "Viswam Backend" cmd /k "npm run server"

echo Starting Frontend...
start "Viswam Frontend" cmd /k "npm run dev"

echo Application launched! Backend running on http://localhost:5000, Frontend launching...
